#!/bin/bash -xv

sdir=/home/ueda/Maildir/new
ddir=/home/ueda/MAIL
tmp=/home/ueda/tmp/$$

cd $sdir || exit 1

######################################
#ファイルのリストを作る
echo *.*.*			|
tr ' ' '\n'			|
#1:ファイル名
awk -F. '{print "@" $1,$0}'	> $tmp-files
#1:UNIX時間 2:ファイル名

######################################
#ファイルのリストに年月日をくっつける
self 1 $tmp-files	|
date -f - "+%Y%m%d"	|
#1:年月日
ycat - $tmp-files	|
#1:年月日 2:UNIX時間 3:ファイル名
delf 2 > $tmp-ymd-file
#1:年月日 2:ファイル名

cd $ddir || exit 1

######################################
#日別のディレクトリを作る
self 1 $tmp-ymd-file	|
uniq			|
xargs -P 100 mkdir -p 

cat $tmp-ymd-file	|
awk -v sd="$sdir" '{print sd "/" $2, "./" $1 "/"}'	|
xargs -P 100 -n 2 cp -p

######################################
#UTF-8に変換

#日別のディレクトリを作る
self 1 $tmp-ymd-file		|
uniq				|
awk '{print $1 ".utf8"}'	|
xargs -P 100 mkdir -p 

#コピー
cat $tmp-ymd-file					|
awk -v sd="$sdir" '{print sd "/" $2, "./" $1 ".utf8/"}'	|
xargs -P 100 -n 2 cp -p

#変換
echo ./*.utf8/*			|
tr ' ' '\n'			|
xargs -n 1 nkf -w --overwrite

rm -f $tmp-*
exit 0
